# Generated by Django 5.2.13 on 2026-06-18 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_flashcard_studysession_studystreak_topicstat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chathistory',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='flashcard',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='studysession',
            options={'ordering': ['-started_at']},
        ),
        migrations.AlterModelOptions(
            name='topicstat',
            options={'ordering': ['-study_count']},
        ),
    ]
